// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRfJcdsuUo6T0lIUGppp0h7GPMGPnC5zU',
    appId: '1:383352949608:web:498687d7a3ad83c2d8a4dd',
    messagingSenderId: '383352949608',
    projectId: 'satiproject1-dca05',
    authDomain: 'satiproject1-dca05.firebaseapp.com',
    storageBucket: 'satiproject1-dca05.appspot.com',
    measurementId: 'G-10P01DV5K8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX8-3lkbBixok4vC7NgWHZMaRfnM1ipaE',
    appId: '1:383352949608:android:5f67482d877d32c8d8a4dd',
    messagingSenderId: '383352949608',
    projectId: 'satiproject1-dca05',
    storageBucket: 'satiproject1-dca05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmuW6pyA_tYnxkWe-tMS1UoHUNnirzAdc',
    appId: '1:383352949608:ios:1384fe14f62d9be6d8a4dd',
    messagingSenderId: '383352949608',
    projectId: 'satiproject1-dca05',
    storageBucket: 'satiproject1-dca05.appspot.com',
    iosClientId: '383352949608-hhgnciut73m7tsl86mpa4evl2n2a0oee.apps.googleusercontent.com',
    iosBundleId: 'com.example.sati1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmuW6pyA_tYnxkWe-tMS1UoHUNnirzAdc',
    appId: '1:383352949608:ios:1384fe14f62d9be6d8a4dd',
    messagingSenderId: '383352949608',
    projectId: 'satiproject1-dca05',
    storageBucket: 'satiproject1-dca05.appspot.com',
    iosClientId: '383352949608-hhgnciut73m7tsl86mpa4evl2n2a0oee.apps.googleusercontent.com',
    iosBundleId: 'com.example.sati1',
  );
}
